### ISSUE TITLE
Try-Ceph failing in: TASK [common : Installing Ceph packages] 

### ISSUE THREAD

**Issue by ColumGaynor** [ksingh7/Try-Ceph#10]
Getting following failure. Log File also attached. Appreciate any guidance how to work around this. Sorry total newbie to Ansible.
![screenshot from 2017-02-23 22-28-01](https://cloud.githubusercontent.com/assets/5797613/23277674/6b70da68-fa17-11e6-863f-abfd7c0db3fe.png)

Log File:
[Try_Ceph_ErrorLog.txt](https://github.com/ksingh7/Try-Ceph/files/797664/Try_Ceph_ErrorLog.txt)

**Comment by isaldarriaga** [comment]
Same problem. refer to http://tracker.ceph.com/issues/16916

how to fix?

**Comment by anvik** [comment]
I am also seeing same problem. Any resolution found?
